### ISSUE TITLE
Something went wrong while importing Openpose 

### ISSUE THREAD

**Issue by mesakarghm** [chonyy/AI-basketball-analysis#10]
While performing analysis on Video, I run into the following error. The app works with the pictures, the following problem arises only when video is selected. 

Something went wrong when importing OpenPose
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "C:\Users\Devil\AppData\Roaming\Python\Python37\site-packages\werkzeug\wsgi.py", line 506, in __next__
    return self._next()
  File "C:\Users\Devil\AppData\Roaming\Python\Python37\site-packages\werkzeug\wrappers\base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "D:\GritFeat\CV\AI-basketball-analysis-master\src\app_helper.py", line 19, in getVideoStream
    datum, opWrapper = openpose_init()
  File "D:\GritFeat\CV\AI-basketball-analysis-master\src\utils.py", line 47, in openpose_init
    raise e
  File "D:\GritFeat\CV\AI-basketball-analysis-master\src\utils.py", line 39, in openpose_init
    import OpenPose.Release.pyopenpose as op
ModuleNotFoundError: No module named 'OpenPose.Release.pyopenpose'

**Comment by chonyy** [comment]
Hi, sorry for the late reply.

Do you have OpenPose properly installed on your device?
If you don't,  [![](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/hardik0/AI-basketball-analysis-on-google-colab/blob/master/AI_basketball_analysis_google_colab.ipynb) this is a notebook that walks you through the process to get this project up and running.

Please tell me if the issue is solved!

**Comment by Vazzzi** [comment]
Hello @chonyy, after following the attached notebook instructions I also get the following error:
ImportError: libopenpose.so.1.6.0: cannot open shared object file: No such file or directory

**Comment by xugaoxiang** [comment]
Same problem, ubuntu 18.04.

**Comment by yukun7273** [comment]
i had the same problem in windows10.  and when i move the project in openpose/build, i can find the the **pyopenpose**, but it doesn't work. when debug the result shows datum
![image](https://user-images.githubusercontent.com/65547986/117984553-84bfce00-b36a-11eb-99fd-08f8524b5725.png).

**Comment by xugaoxiang** [comment]
I solve the problem. Compile the [source](https://github.com/CMU-Perceptual-Computing-Lab/openpose) (I use the release 1.7.0 and python 3.7) and then copy the compiled pyopenpose.cpython-37m-x86_64-linux-gnu.so to folder OpenPose/openpose

and change the code src/utils.py about Line 135 from 

`opWrapper.emplaceAndPop([datum])`

to

`opWrapper.emplaceAndPop(op.VectorDatum([datum]))`

Please access [my openpose blog](https://xugaoxiang.com/2020/10/26/openpose-build/) for details.

**Comment by chonyy** [comment]
Hi @xugaoxiang, 

Thanks a lot for the information! I will update the instructions on my repo following your solution.
The compilation of OpenPose is always troublesome, I'm glad that you could figure out the solution.
It seems like there's no efficient way to share a project that included OpenPose, recompiling is always required.

**Comment by xugaoxiang** [comment]
This is a great project, thank you.

**Comment by or-toledano** [comment]
> I solve the problem. Compile the [source](https://github.com/CMU-Perceptual-Computing-Lab/openpose) (I use the release 1.7.0 and python 3.7) and then copy the compiled pyopenpose.cpython-37m-x86_64-linux-gnu.so to folder OpenPose/openpose
> 
> and change the code src/utils.py about Line 135 from
> 
> `opWrapper.emplaceAndPop([datum])`
> 
> to
> 
> `opWrapper.emplaceAndPop(op.VectorDatum([datum]))`
> 
> Please access [my openpose blog](https://xugaoxiang.com/2020/10/26/openpose-build/) for details.

Thanks!
Note that app_helper.py also requires:
            detection, trace = detect_shot(img, trace, width, height, sess, image_tensor, boxes, scores, classes,
                                        num_detections, previous, during_shooting, shot_result, fig, datum, opWrapper, shooting_pose, *op*)
(The addition of an op arg)
which can be obtained by 
    datum, opWrapper, op = openpose_init()
(need to alter openpose_init for this)
