### ISSUE TITLE
erro： import OpenPose.Release.pyopenpose as op ImportError: DLL load failed:

### ISSUE THREAD

**Issue by undefeatedsoul** [chonyy/AI-basketball-analysis#43]
How to solve the following problems：
Traceback (most recent call last):
  File "D:\Miniconda3\envs\TF-openpose\lib\site-packages\werkzeug\wsgi.py", line 462, in __next__
    return self._next()
  File "D:\Miniconda3\envs\TF-openpose\lib\site-packages\werkzeug\wrappers\response.py", line 50, in _iter_encoded
    for item in iterable:
  File "D:\pycharm\PythonProject\AI-basketball\src\app_helper.py", line 19, in getVideoStream
    datum, opWrapper = openpose_init()
  File "D:\pycharm\PythonProject\AI-basketball\src\utils.py", line 46, in openpose_init
    raise e
  File "D:\pycharm\PythonProject\AI-basketball\src\utils.py", line 38, in openpose_init
    import OpenPose.Release.pyopenpose as op
ImportError: DLL load failed: 找不到指定的模块。
I would greatly appreciate it if you could provide some suggestions

**Comment by jatin711-debug** [comment]
any updates or how you resolved it ??

**Comment by Yile516** [comment]
Has this issue been resolved? I'm also having the same problem

**Comment by undefeatedsoul** [comment]
夜雨笙烦
***@***.***



        This is an import issue with OpenPose. You may need to re-import the OpenPose project and compile and link it with CMake, then replace the OpenPose in this project. This should work.


         原始邮件
         
       
发件人：Yile516 ***@***.***&gt;
发件时间：2025年10月20日 19:57
收件人：2784196749 ***@***.***&gt;
抄送：Tianle Shi ***@***.***&gt;, Author ***@***.***&gt;
主题：Re: [chonyy/AI-basketball-analysis] erro： import OpenPose.Release.pyopenpose as op ImportError: DLL load failed: (Issue #43)



Yile516 left a comment (chonyy/AI-basketball-analysis#43)

Has this issue been resolved? I'm also having the same problem
