### ISSUE TITLE
Too slow on web server

### ISSUE THREAD

**Issue by Zames-Chang** [chonyy/AI-basketball-analysis#6]
Since Fast RCNN is a very CPU-bound object detection model, it loop over all image to find out possible. Although it does a lot optimization like Dynamic Programming. It still not a good fit on real time object detection.

I recommend you to use yolo4. I is the fastest object detection right now If I am not wrong.

- [yolo4](https://github.com/AlexeyAB/darknet)

There is python API in file `darknet.py`. Since I don't have datasets for training, I cannot help you to training deep learning model. Sorry~

**Comment by chonyy** [comment]
I know that the efficiency of Faster RCNN is fairly limited. I started with it because of its high accuracy. I need enough accuracy to design the algorithm for this project.
Since I already got a basic structure now, I really should find a way to improve the inference time of each frame. Changing the model to yolov4 would be a really nice approach!
I would work on it once I got time. Thanks!

**Comment by Zames-Chang** [comment]
this is a comparison of accuracy and process speed between different object detection model.
![image](https://user-images.githubusercontent.com/25127764/82991282-03bfd780-a030-11ea-9043-ee277878447d.png)
![image](https://cdn-images-1.medium.com/max/1024/1*EQKFp_c6jMYcDZbIwbEOzA.png)

**Comment by Zames-Chang** [comment]
Fun story, this model is very great. US military use this model on drone to automatically identify enemy and fire them. Because of  this application, he give up object detection field and switch to other research area.

**Comment by AditSoni** [comment]
hey guys can yall gimme a little advice so i can move in the field of machine learning and deep learning
and also i cant run this project ,I am using pop_os ,python 3.6.10 , nvdia gpu

**Comment by chonyy** [comment]
@AditSoni Hey, can you please tell me what error message did you get?

**Comment by AditSoni** [comment]
![Screenshot from 2020-06-07 17-28-43](https://user-images.githubusercontent.com/51469232/83968097-70668c00-a8e4-11ea-96b8-db28b22a8a1e.png)
pyopenpose module fails

**Comment by AditSoni** [comment]
and now I have got a new error:


Something went wrong when importing OpenPose
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/src/app_helper.py", line 19, in getVideoStream
    datum, opWrapper = openpose_init()
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/src/utils.py", line 443, in openpose_init
    raise e
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/src/utils.py", line 440, in openpose_init
    import pyopenpose as op
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/pyopenpose/__init__.py", line 1, in <module>
    from .core import OPose
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/pyopenpose/core.py", line 1, in <module>
    from .utils import ClassDict
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/pyopenpose/utils/__init__.py", line 2, in <module>
    from . import op_json
  File "/home/aditsoni/Workspace/python/Basketball_shot_estimation/AI-basketball-analysis/venv/lib/python3.6/site-packages/pyopenpose/utils/op_json.py", line 7, in <module>
    from classdict import ClassDict
ModuleNotFoundError: No module named 'classdict'

**Comment by chonyy** [comment]
@AditSoni Hi, I think this problem has something to do with your environment setup, please try it on Windows or Ubuntu.
Also, feel free to start a new issue since this thread is focusing on how to improve the efficiency.

**Comment by AditSoni** [comment]
requirements.txt doesnt contain all the modules used by this project , can you update it please?

**Comment by chonyy** [comment]
@AditSoni Hi, please start a new issue if you encounter any further problems. Thanks!
